name: 'Create File Node v16'
description: 'Create a file using Node v16'
branding:
  icon: 'file'  
  color: 'green'
inputs:
  path:
    description: 'Path from cwd where file is to be created'
    required: true
    default: ''
  file:
    description: 'The name of the file to be created with extention'
    required: true
  content:
    description: 'The content of the file'
    required: true
    default: ''
runs:
  using: 'node16'
  main: 'index.js'
